version: 2
updates:
  # Python dependencies from requirements.txt
  - package-ecosystem: "pip"
    directory: "/"            # Root folder containing requirements.txt
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "deps"

  # GitHub Actions workflows
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "chore(actions)"
